## Tutorial 12 Gradient Descent

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [84]:
df = pd.read_csv('tutorial12_insurance_data.csv')
df

    age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df.bought_insurance, test_size=0.2, random_state=25)

In [11]:
len(X_train)

22

In [12]:
len(X_test)

6

In [13]:
X_train_scalled = X_train.copy()
X_train_scalled['age'] = X_train_scalled['age'] / 100

In [14]:
X_test_scalled = X_test.copy()
X_test_scalled['age'] = X_test_scalled['age'] / 100

In [15]:
X_train_scalled

     age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [16]:
X_test_scalled

     age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [17]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=((2,)), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

C:\Users\Dell-Precession\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train_scalled, y_train, epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 766ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7050
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7028
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7025
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7017
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7003
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7000
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6989
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6986
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6969
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6958
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6955
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6948
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.6938
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6935
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6906
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - loss: 0.6902
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6893
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6877
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6859
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6853
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6849
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6846
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.6840
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6838
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6835
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6832
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6829
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6826
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6823
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6820
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6817
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6814
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6811
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6808
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6805
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6803
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6800
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6797
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6794
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.6791
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6788
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.6786
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6783
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5000 - loss: 0.6780
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6777
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6775
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6769
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6766
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6764
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6761
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6758
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.6756
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6753
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6750
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6748
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6745
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6742
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6740
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6737
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.5000 - loss: 0.6735
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6732
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6730
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6727
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6724
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6722
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6719
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6717
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6714
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6712
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6709
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6707
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6704
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6702
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6699
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6697
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.6695
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6692
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6690
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6687
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6685
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6683
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6680
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6661
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6659
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6657
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6655
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6652
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6650
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6648
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6646
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6643
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6641
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6639
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6637
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.6635
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6632
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6630
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6628
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6626
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6624
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6622
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6620
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6617
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6615
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6613
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6611
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6609
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5455 - loss: 0.6607
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - loss: 0.6605
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6603
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6601
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - loss: 0.6599
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6597
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5455 - loss: 0.6595
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6593
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.6591
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6589
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6587
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.6585
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6583
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5455 - loss: 0.6581
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6579
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6577
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5455 - loss: 0.6575
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6573
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5455 - loss: 0.6571
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.6569
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5455 - loss: 0.6568
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5455 - loss: 0.6566
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6564
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5455 - loss: 0.6562
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5455 - loss: 0.6560
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5455 - loss: 0.6558
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5455 - loss: 0.6556
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5455 - loss: 0.6555
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5455 - loss: 0.6553
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6551
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.6549
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.6547
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6545
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6544
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5455 - loss: 0.6542
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6540
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6538
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6537
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5455 - loss: 0.6535
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5455 - loss: 0.6533
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6531
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5455 - loss: 0.6530
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6528
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - loss: 0.6526
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5455 - loss: 0.6525
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5455 - loss: 0.6523
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5455 - loss: 0.6521
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5455 - loss: 0.6519
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5455 - loss: 0.6518
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5455 - loss: 0.6516
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6515
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5455 - loss: 0.6513
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - loss: 0.6511
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5455 - loss: 0.6510
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6508
Epoch 229/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6506
Epoch 230/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - loss: 0.6505
Epoch 231/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6503

In [40]:
model.evaluate(X_test_scalled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.3550

[0.35497763752937317, 1.0]

In [41]:
model.predict(X_test_scalled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [42]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [43]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

##### Coef is the one which which has w1 and w2 etc. And intercept is the bias

### Below we can see how we can add the same in plane python code

In [44]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))

In [45]:
sigmoid(18)

0.9999999847700205

In [46]:
sigmoid(0)

0.5

In [47]:
sigmoid(-5)

0.0066928509242848554

In [55]:
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [56]:
def predicted_function(age, affordability):
    weighted_sum = coef[0] * age + coef[1] * affordability + intercept
    return sigmoid(weighted_sum)

In [57]:
X_test_scalled

     age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [58]:
predicted_function(.47, 1)

C:\Users\Dell-Precession\AppData\Local\Temp\ipykernel_3580\3918314859.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))

0.7054847702382996

In [60]:
predicted_function(.18, 1)

C:\Users\Dell-Precession\AppData\Local\Temp\ipykernel_3580\3918314859.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))

0.35569571637887243

In [63]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [64]:
def sigmoid_numpy(X):
    return 1 / (1 + np.exp(-X))

In [66]:
sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

In [79]:
def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
    # we need to find w1, w2 and bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)
        w1d = (1/n)*np.dot(np.transpose(age), (y_predicted - y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted - y_true))
        bias_d = np.mean(y_predicted - y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d
        print(f'epoch:{i}, w1:{w1}, w2:{w2}, loss:{loss}')
        if loss <=loss_threshold:
            break
    return w1, w2, bias

In [80]:
X_train_scalled

     age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [81]:
gradient_descent(X_train_scalled['age'], X_train_scalled['affordibility'], y_train, 1000, 0.4631)

epoch:0, w1:0.974907633470177, w2:0.948348125394529, loss:0.7113403233723417
epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, loss:0.681264778737757
epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, loss:0.6591474252715025
epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, loss:0.6431523291301917
epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, loss:0.6316873063379158
epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, loss:0.623471707997592
epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, loss:0.6175321183044205
epoch:7, w1:0.93047170420295, w2:0.7983920007454487, loss:0.6131591858705934
epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, loss:0.6098518179750948
epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, loss:0.6072639970231438
epoch:10, w1:0.9521448361628082, w2:0.8002404280558159, loss:0.6051606942838051
epoch:11, w1:0.9619014360798376, w2:0.8047697991276092, loss:0.6033841405177724
epoch:12, w1:0.9725437902239876, w2:0.8105978078160995, loss:0.6018292976282692
epoch:13, w1:0.9839042828641819, w2:0.8174345999952901, loss:0.6004266142491015
epoch:14, w1:0.9958464546516588, w2:0.8250447751055391, loss:0.5991301804031037
epoch:15, w1:1.0082595007242081, w2:0.8332379503132499, loss:0.5979097221992564
epoch:16, w1:1.0210536111133566, w2:0.8418606908070436, loss:0.5967452540340851
epoch:17, w1:1.034156080666481, w2:0.8507897246509063, loss:0.5956235357679642
epoch:18, w1:1.0475080939682688, w2:0.8599263049589658, loss:0.5945357398126384
epoch:19, w1:1.0610620872868053, w2:0.8691915649552581, loss:0.5934759216594547
epoch:20, w1:1.0747795953648005, w2:0.8785227146485403, loss:0.5924400203169505
epoch:21, w1:1.0886295007650375, w2:0.8878699408379153, loss:0.5914252065214394
epoch:22, w1:1.1025866146156011, w2:0.8971938890119441, loss:0.5904294583596238
epoch:23, w1:1.1166305284975315, w2:0.9064636231844676, loss:0.5894512852039241
epoch:24, w1:1.130744687166233, w2:0.9156549761872753, loss:0.5884895481881011
epoch:25, w1:1.1449156405234902, w2:0.9247492176815199, loss:0.5875433434377384
epoch:26, w1:1.1591324407175467, w2:0.9337319799254573, loss:0.5866119260562087
epoch:27, w1:1.1733861565198167, w2:0.9425923921787205, loss:0.5856946605640079
epoch:28, w1:1.1876694823356402, w2:0.9513223836938425, loss:0.5847909885040025
epoch:29, w1:1.2019764234961199, w2:0.9599161227563919, loss:0.5839004071862915
epoch:30, w1:1.2163020429886013, w2:0.9683695654077998, loss:0.5830224556644095
epoch:31, w1:1.2306422576428844, w2:0.9766800925300213, loss:0.5821567054089575
epoch:32, w1:1.244993674111329, w2:0.9848462180774323, loss:0.5813027540359855
epoch:33, w1:1.2593534568600255, w2:0.9928673545729692, loss:0.5804602210251408
epoch:34, w1:1.2737192219062514, w2:1.0007436246821175, loss:0.5796287447370064
epoch:35, w1:1.2880889512619975, w2:1.0084757098569885, loss:0.57880798028165
epoch:36, w1:1.3024609240300042, w2:1.0160647288004139, loss:0.5779975979476322
epoch:37, w1:1.3168336608930384, w2:1.0235121399165894, loss:0.5771972820026156
epoch:38, w1:1.3312058793761508, w2:1.0308196630555955, loss:0.5764067297427645
epoch:39, w1:1.3455764577755067, w2:1.03798921677727, loss:0.5756256507109632
epoch:40, w1:1.3599444060604624, w2:1.0450228680985851, loss:0.5748537660316542
epoch:41, w1:1.3743088423875545, w2:1.0519227922827652, loss:0.5740908078281305
epoch:42, w1:1.3886689741318716, w2:1.0586912407061275, loss:0.5733365186998219
epoch:43, w1:1.4030240825556768, w2:1.065330515222758, loss:0.5725906512447178
epoch:44, w1:1.4173735104064382, w2:1.0718429477560005, loss:0.5718529676170188
epoch:45, w1:1.4317166518748927, w2:1.0782308840940895, loss:0.5711232391133308
epoch:46, w1:1.4460529444550507, w2:1.0844966710669584, loss:0.5704012457828124
epoch:47, w1:1.4603818623375084, w2:1.0906426464418717, loss:0.5696867760580651
epoch:48, w1:1.474702911039356, w2:1.0966711310047097, loss:0.5689796264044564
epoch:49, w1:1.4890156230318012, w2:1.1025844223976542, loss:0.5682796009861607
epoch:50, w1:1.503319554173139, w2:1.108384790367645, loss:0.5675865113475955
epoch:51, w1:1.5176142807921111, w2:1.1140744731472638, loss:0.5669001761092021
epoch:52, w1:1.5318993972968091, w2:1.1196556747438646, loss:0.566220420676692
epoch:53, w1:1.546174514208496, w2:1.1251305629563741, loss:0.5655470769630154
epoch:54, w1:1.5604392565392238, w2:1.1305012679742994, loss:0.5648799831223866
epoch:55, w1:1.5746932624478314, w2:1.1357698814417572, loss:0.5642189832957764
epoch:56, w1:1.5889361821215457, w2:1.1409384558921223, loss:0.5635639273673236
epoch:57, w1:1.6031676768405996, w2:1.1460090044772484, loss:0.562914670731162
epoch:58, w1:1.6173874181914885, w2:1.150983500930006, loss:0.5622710740681858
epoch:59, w1:1.6315950874010996, w2:1.155863879710811, loss:0.5616330031323111
epoch:60, w1:1.6457903747692835, w2:1.1606520362984267, loss:0.5610003285458062
epoch:61, w1:1.6599729791817353, w2:1.1653498275930778, loss:0.5603729256032908
epoch:62, w1:1.6741426076885264, w2:1.1699590724061661, loss:0.5597506740840237
epoch:63, w1:1.6882989751364197, w2:1.1744815520159209, loss:0.5591334580721091
epoch:64, w1:1.7024418038453646, w2:1.1789190107723873, loss:0.5585211657842806
epoch:65, w1:1.7165708233213919, w2:1.1832731567384374, loss:0.5579136894049259
epoch:66, w1:1.7306857699995972, w2:1.1875456623561378, loss:0.5573109249280388
epoch:67, w1:1.744786387012096, w2:1.1917381651299463, loss:0.556712772005794
epoch:68, w1:1.7588724239767908, w2:1.1958522683199346, loss:0.5561191338034575
epoch:69, w1:1.7729436368035707, w2:1.199889541639625, loss:0.5555299168603557
epoch:70, w1:1.786999787515191, w2:1.2038515219541523, loss:0.55494503095664
epoch:71, w1:1.8010406440805895, w2:1.2077397139753707, loss:0.5543643889855958
epoch:72, w1:1.815065980258806, w2:1.21155559095125, loss:0.5537879068312537
epoch:73, w1:1.8290755754520085, w2:1.2153005953475013, loss:0.5532155032510755
epoch:74, w1:1.8430692145663952, w2:1.2189761395198406, loss:0.5526470997634942
epoch:75, w1:1.857046687879965, w2:1.2225836063756854, loss:0.5520826205400979
epoch:76, w1:1.8710077909163219, w2:1.2261243500243837, loss:0.5515219923022593
epoch:77, w1:1.8849523243238275, w2:1.2295996964153224, loss:0.5509651442220168
epoch:78, w1:1.898880093759531, w2:1.2330109439634602, loss:0.5504120078270269
epoch:79, w1:1.9127909097773987, w2:1.2363593641619885, loss:0.5498625169094129
epoch:80, w1:1.9266845877204517, w2:1.2396462021819508, loss:0.5493166074383391
epoch:81, w1:1.9405609476164691, w2:1.2428726774587495, loss:0.5487742174761587
epoch:82, w1:1.9544198140769822, w2:1.2460399842655545, loss:0.5482352870979753
epoch:83, w1:1.968261016199314, w2:1.2491492922736824, loss:0.5476997583144769
epoch:84, w1:1.9820843874714607, w2:1.252201747100074, loss:0.5471675749979029
epoch:85, w1:1.995889765679638, w2:1.2551984708420285, loss:0.5466386828110088
epoch:86, w1:2.0096769928183367, w2:1.2581405625993878, loss:0.5461130291389041
epoch:87, w1:2.023445915002755, w2:1.2610290989843815, loss:0.545590563023641
epoch:88, w1:2.037196382383489, w2:1.2638651346193672, loss:0.5450712351014357
epoch:89, w1:2.0509282490633733, w2:1.2666497026227028, loss:0.5445549975424178
epoch:90, w1:2.0646413730163813, w2:1.2693838150830055, loss:0.5440418039927909
epoch:91, w1:2.0783356160084976, w2:1.2720684635220503, loss:0.5435316095193146
epoch:92, w1:2.092010843520487, w2:1.2747046193465692, loss:0.5430243705560023
epoch:93, w1:2.1056669246724873, w2:1.2772932342892063, loss:0.5425200448529465
epoch:94, w1:2.1193037321503643, w2:1.2798352408388918, loss:0.5420185914271816
epoch:95, w1:2.1329211421337653, w2:1.282331552660889, loss:0.5415199705154982
epoch:96, w1:2.1465190342258187, w2:1.2847830650067702, loss:0.5410241435291299
epoch:97, w1:2.1600972913844236, w2:1.2871906551145709, loss:0.5405310730102341
epoch:98, w1:2.173655799855084, w2:1.2895551825993699, loss:0.5400407225900913
epoch:99, w1:2.1871944491052364, w2:1.2918774898345378, loss:0.5395530569489538
epoch:100, w1:2.200713131760032, w2:1.2941584023238903, loss:0.5390680417774752
epoch:101, w1:2.2142117435395288, w2:1.2963987290649803, loss:0.5385856437396539
epoch:102, w1:2.227690183197251, w2:1.298599262903754, loss:0.5381058304372313
epoch:103, w1:2.241148352460086, w2:1.300760780880796, loss:0.5376285703754836
epoch:104, w1:2.2545861559694704, w2:1.302884044569378, loss:0.5371538329303491
epoch:105, w1:2.268003501223843, w2:1.3049698004055226, loss:0.5366815883168389
epoch:106, w1:2.281400298522321, w2:1.30701878001029, loss:0.5362118075586769
epoch:107, w1:2.294776460909571, w2:1.3090317005044871, loss:0.5357444624591193
epoch:108, w1:2.308131904121845, w2:1.3110092648159952, loss:0.5352795255729065
epoch:109, w1:2.3214665465341486, w2:1.3129521619799067, loss:0.5348169701793002
epoch:110, w1:2.334780309108516, w2:1.3148610674316565, loss:0.5343567702561651
epoch:111, w1:2.3480731153433556, w2:1.3167366432933292, loss:0.5338989004550466
epoch:112, w1:2.361344891223853, w2:1.318579538653317, loss:0.5334433360772121
epoch:113, w1:2.3745955651733888, w2:1.3203903898394993, loss:0.5329900530506113
epoch:114, w1:2.387825068005961, w2:1.3221698206861112, loss:0.532539027907722
epoch:115, w1:2.4010333328795768, w2:1.3239184427944621, loss:0.5320902377642434
epoch:116, w1:2.4142202952505927, w2:1.3256368557876617, loss:0.5316436602986057
epoch:117, w1:2.427385892828985, w2:1.3273256475595065, loss:0.5311992737322607
epoch:118, w1:2.440530065534521, w2:1.328985394517677, loss:0.5307570568107249
epoch:119, w1:2.4536527554538115, w2:1.3306166618213877, loss:0.5303169887853427
epoch:120, w1:2.46675390679823, w2:1.332220003613633, loss:0.5298790493957434
epoch:121, w1:2.479833465862666, w2:1.3337959632481655, loss:0.5294432188529623
epoch:122, w1:2.4928913809851023, w2:1.3353450735113397, loss:0.5290094778232023
epoch:123, w1:2.505927602506996, w2:1.336867856838949, loss:0.5285778074122077
epoch:124, w1:2.518942082734439, w2:1.3383648255281848, loss:0.5281481891502279
epoch:125, w1:2.5319347759000843, w2:1.3398364819448387, loss:0.5277206049775486
epoch:126, w1:2.5449056381258233, w2:1.341283318725866, loss:0.5272950372305655
epoch:127, w1:2.557854627386187, w2:1.3427058189774277, loss:0.5268714686283816
epoch:128, w1:2.570781703472466, w2:1.3441044564685243, loss:0.5264498822599072
epoch:129, w1:2.583686827957526, w2:1.345479695820328, loss:0.5260302615714416
epoch:130, w1:2.596569964161304, w2:1.346831992691322, loss:0.5256125903547197
epoch:131, w1:2.6094310771169726, w2:1.3481617939583521, loss:0.5251968527354035
epoch:132, w1:2.6222701335377554, w2:1.3494695378936876, loss:0.524783033162003
epoch:133, w1:2.635087101784378, w2:1.3507556543381913, loss:0.5243711163952075
epoch:134, w1:2.647881951833145, w2:1.3520205648706964, loss:0.5239610874976152
epoch:135, w1:2.660654655244622, w2:1.353264682973678, loss:0.5235529318238407
epoch:136, w1:2.6734051851329177, w2:1.3544884141953148, loss:0.5231466350109902
epoch:137, w1:2.686133516135547, w2:1.3556921563080242, loss:0.5227421829694884
epoch:138, w1:2.6988396243838655, w2:1.3568762994635601, loss:0.5223395618742417
epoch:139, w1:2.7115234874740595, w2:1.3580412263447545, loss:0.5219387581561296
epoch:140, w1:2.724185084438686, w2:1.3591873123139828, loss:0.521539758493806
epoch:141, w1:2.736824395718745, w2:1.3603149255584348, loss:0.5211425498058037
epoch:142, w1:2.7494414031362733, w2:1.3614244272322646, loss:0.5207471192429267
epoch:143, w1:2.7620360898674554, w2:1.3625161715956964, loss:0.5203534541809204
epoch:144, w1:2.7746084404162294, w2:1.363590506151157, loss:0.5199615422134104
epoch:145, w1:2.787158440588389, w2:1.364647771776508, loss:0.5195713711450981
epoch:146, w1:2.7996860774661636, w2:1.3656883028554423, loss:0.5191829289852049
epoch:147, w1:2.812191339383268, w2:1.3667124274051172, loss:0.5187962039411522
epoch:148, w1:2.824674215900416, w2:1.3677204672010856, loss:0.5184111844124737
epoch:149, w1:2.8371346977812824, w2:1.3687127378995887, loss:0.5180278589849453
epoch:150, w1:2.8495727769689085, w2:1.3696895491572745, loss:0.5176462164249294
epoch:151, w1:2.861988446562542, w2:1.3706512047484, loss:0.5172662456739209
epoch:152, w1:2.8743817007948973, w2:1.3715980026795769, loss:0.5168879358432925
epoch:153, w1:2.886752535009837, w2:1.3725302353021163, loss:0.5165112762092271
epoch:154, w1:2.899100945640455, w2:1.373448189422031, loss:0.5161362562078318
epoch:155, w1:2.9114269301875644, w2:1.3743521464077455, loss:0.515762865430428
epoch:156, w1:2.9237304871985708, w2:1.3752423822955708, loss:0.5153910936190104
epoch:157, w1:2.9360116162467342, w2:1.376119167892991, loss:0.515020930661866
epoch:158, w1:2.9482703179108047, w2:1.3769827688798149, loss:0.5146523665893518
epoch:159, w1:2.960506593755025, w2:1.3778334459072408, loss:0.514285391569821
epoch:160, w1:2.9727204463094963, w2:1.3786714546948804, loss:0.5139199959056945
epoch:161, w1:2.984911879050898, w2:1.3794970461257903, loss:0.5135561700296716
epoch:162, w1:2.9970808963835545, w2:1.3803104663395542, loss:0.5131939045010747
epoch:163, w1:3.0092275036208402, w2:1.3811119568234618, loss:0.5128331900023233
epoch:164, w1:3.0213517069669225, w2:1.3819017545018246, loss:0.5124740173355311
epoch:165, w1:3.0334535134988276, w2:1.382680091823474, loss:0.5121163774192251
epoch:166, w1:3.045532931148832, w2:1.3834471968474789, loss:0.5117602612851783
epoch:167, w1:3.0575899686871653, w2:1.384203293327124, loss:0.511405660075352
epoch:168, w1:3.069624635705023, w2:1.384948600792189, loss:0.5110525650389491
epoch:169, w1:3.081636942597884, w2:1.385683334629563, loss:0.5107009675295656
epoch:170, w1:3.093626900549122, w2:1.386407706162234, loss:0.5103508590024443
epoch:171, w1:3.105594521513913, w2:1.387121922726688, loss:0.5100022310118232
epoch:172, w1:3.117539818203424, w2:1.387826187748753, loss:0.5096550752083747
epoch:173, w1:3.1294628040692873, w2:1.3885207008179221, loss:0.5093093833367357
epoch:174, w1:3.141363493288346, w2:1.3892056577601883, loss:0.5089651472331199
epoch:175, w1:3.1532419007476733, w2:1.389881250709425, loss:0.5086223588230153
epoch:176, w1:3.165098042029856, w2:1.390547668177342, loss:0.5082810101189588
epoch:177, w1:3.176931933398537, w2:1.3912050951220503, loss:0.5079410932183875
epoch:178, w1:3.188743591784215, w2:1.3918537130152622, loss:0.5076026003015645
epoch:179, w1:3.200533034770296, w2:1.3924936999081612, loss:0.5072655236295737
epoch:180, w1:3.212300280579388, w2:1.3931252304959654, loss:0.5069298555423847
epoch:181, w1:3.2240453480598403, w2:1.3937484761812156, loss:0.5065955884569808
epoch:182, w1:3.235768256672519, w2:1.3943636051358148, loss:0.5062627148655543
epoch:183, w1:3.2474690264778157, w2:1.394970782361845, loss:0.505931227333758
epoch:184, w1:3.2591476781228836, w2:1.3955701697511878, loss:0.5056011184990193
epoch:185, w1:3.270804232829102, w2:1.3961619261439753, loss:0.505272381068909
epoch:186, w1:3.2824387123797556, w2:1.3967462073858943, loss:0.5049450078195657
epoch:187, w1:3.294051139107937, w2:1.3973231663843697, loss:0.5046189915941715
epoch:188, w1:3.3056415358846545, w2:1.3978929531636493, loss:0.5042943253014793
epoch:189, w1:3.317209926107157, w2:1.3984557149188142, loss:0.5039710019143897
epoch:190, w1:3.3287563336874557, w2:1.3990115960687382, loss:0.5036490144685731
epoch:191, w1:3.340280783041054, w2:1.3995607383080155, loss:0.5033283560611389
epoch:192, w1:3.351783299075871, w2:1.400103280657881, loss:0.5030090198493474
epoch:193, w1:3.3632639071813593, w2:1.4006393595161428, loss:0.502690999049364
epoch:194, w1:3.3747226332178184, w2:1.401169108706148, loss:0.502374286935055
epoch:195, w1:3.3861595035058896, w2:1.4016926595248012, loss:0.5020588768368214
epoch:196, w1:3.3975745448162384, w2:1.4022101407896574, loss:0.5017447621404708
epoch:197, w1:3.408967784359416, w2:1.4027216788851056, loss:0.5014319362861261
epoch:198, w1:3.4203392497759015, w2:1.4032273978076624, loss:0.5011203927671694
epoch:199, w1:3.4316889691263146, w2:1.4037274192103975, loss:0.5008101251292182
epoch:200, w1:3.443016970881803, w2:1.4042218624465033, loss:0.5005011269691375
epoch:201, w1:3.4543232839145968, w2:1.4047108446120309, loss:0.5001933919340792
epoch:202, w1:3.4656079374887283, w2:1.4051944805878065, loss:0.4998869137205552
epoch:203, w1:3.4768709612509157, w2:1.4056728830805474, loss:0.499581686073539
epoch:204, w1:3.4881123852216054, w2:1.4061461626631908, loss:0.4992777027855931
epoch:205, w1:3.4993322397861726, w2:1.406614427814455, loss:0.4989749576960279
epoch:206, w1:3.510530555686274, w2:1.407077784957646, loss:0.4986734446900829
epoch:207, w1:3.5217073640113545, w2:1.407536338498725, loss:0.49837315769813556
epoch:208, w1:3.5328626961903016, w2:1.4079901908636536, loss:0.49807409069493364
epoch:209, w1:3.5439965839832466, w2:1.4084394425350295, loss:0.49777623769885115
epoch:210, w1:3.5551090594735104, w2:1.4088841920880264, loss:0.49747959277116743
epoch:211, w1:3.5662001550596885, w2:1.4093245362256548, loss:0.4971841500153676
epoch:212, w1:3.577269903447877, w2:1.4097605698133546, loss:0.4968899035764641
epoch:213, w1:3.5883183376440364, w2:1.4101923859129344, loss:0.49659684764033973
epoch:214, w1:3.5993454909464844, w2:1.4106200758158696, loss:0.49630497643310856
epoch:215, w1:3.610351396938527, w2:1.4110437290759732, loss:0.49601428422049737
epoch:216, w1:3.6213360894812157, w2:1.4114634335414504, loss:0.4957247653072439
epoch:217, w1:3.6322996027062318, w2:1.4118792753863514, loss:0.49543641403651506
epoch:218, w1:3.6432419710088983, w2:1.4122913391414305, loss:0.49514922478933926
epoch:219, w1:3.6541632290413135, w2:1.4126997077244283, loss:0.4948631919840572
epoch:220, w1:3.6650634117056042, w2:1.4131044624697842, loss:0.49457831007578845
epoch:221, w1:3.6759425541473023, w2:1.4135056831577921, loss:0.4942945735559119
epoch:222, w1:3.6868006917488327, w2:1.4139034480432113, loss:0.49401197695156235
epoch:223, w1:3.6976378601231215, w2:1.4142978338833405, loss:0.49373051482514135
epoch:224, w1:3.7084540951073124, w2:1.4146889159655687, loss:0.49345018177384004
epoch:225, w1:3.719249432756598, w2:1.4150767681344103, loss:0.49317097242917785
epoch:226, w1:3.7300239093381586, w2:1.4154614628180373, loss:0.4928928814565522
epoch:227, w1:3.740777561325208, w2:1.4158430710543157, loss:0.4926159035548014
epoch:228, w1:3.751510425391147, w2:1.4162216625163582, loss:0.4923400334557782
epoch:229, w1:3.7622225384038157, w2:1.4165973055376, loss:0.4920652659239369
epoch:230, w1:3.772913937419856, w2:1.4169700671364103, loss:0.4917915957559304
epoch:231, w1:3.783584659679165, w2:1.417340013040245, loss:0.49151901778021734
epoch:232, w1:3.7942347425994543, w2:1.4177072077093518, loss:0.4912475268566808
epoch:233, w1:3.804864223770903, w2:1.4180717143600363, loss:0.4909771178762567
epoch:234, w1:3.8154731409509055, w2:1.418433594987496, loss:0.4907077857605718
epoch:235, w1:3.8260615320589157, w2:1.4187929103882317, loss:0.49043952546159064
epoch:236, w1:3.83662943517138, w2:1.4191497201820455, loss:0.4901723319612717
epoch:237, w1:3.8471768885167634, w2:1.41950408283363, loss:0.4899062002712329
epoch:238, w1:3.857703930470663, w2:1.4198560556737607, loss:0.48964112543242444
epoch:239, w1:3.8682105995510105, w2:1.4202056949200956, loss:0.48937710251481087
epoch:240, w1:3.8786969344133597, w2:1.4205530556975927, loss:0.48911412661705983
epoch:241, w1:3.8891629738462594, w2:1.4208981920585493, loss:0.48885219286623943
epoch:242, w1:3.8996087567667086, w2:1.4212411570022738, loss:0.48859129641752214
epoch:243, w1:3.910034322215694, w2:1.4215820024943946, loss:0.48833143245389626
epoch:244, w1:3.920439709353808, w2:1.4219207794858135, loss:0.48807259618588394
epoch:245, w1:3.930824957456947, w2:1.4222575379313118, loss:0.48781478285126634
epoch:246, w1:3.9411901059120837, w2:1.422592326807813, loss:0.4875579877148143
epoch:247, w1:3.9515351942131214, w2:1.422925194132311, loss:0.4873022060680255
epoch:248, w1:3.9618602619568177, w2:1.4232561869794709, loss:0.487047433228868
epoch:249, w1:3.972165348838788, w2:1.4235853514989025, loss:0.4867936645415293

(np.float64(5.051047623653049),
 np.float64(1.4569794548473887),
 np.float64(-2.9596534546250037))

In [82]:
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

##### We can see both results are near. Plan code and tensor flow gives same w1, w2 and bias